FROM arm32v7/ubuntu:latest

MAINTAINER cade <cade.call@mediciventures.com>

EXPOSE $RPCPORT

EXPOSE $PORT

RUN useradd -ms /bin/bash shahepay

RUN mkdir /etc/shahepay

RUN mkdir /var/lib/shahepay

RUN chown shahepay:shahepay /etc/shahepay /var/lib/shahepay

WORKDIR /home/shahepay

COPY --chown=shahepay:shahepay linux64/* ./run.sh /home/shahepay/

USER shahepay

CMD ["/home/shahepay/run.sh"]
